pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile.build'
            dir 'jenkins/image/'            
            additionalBuildArgs  '--build-arg version=1.0.2'
            args '-v /home/jenkins/.kube:/home/jenkins/.kube/'
        }
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '10'))
        disableConcurrentBuilds()
        timestamps()
        ansiColor('xterm')
    }

    environment {
        APP_PATH = "calc_app/"
        KUBECONFIG = '/home/jenkins/.kube/config'
    }

    stages {
        stage('Build') {
            steps {
                dir(APP_PATH) {
                    sh """
                    sudo docker build -t test -f Dockerfile .
                    """
                }
            }
        }

        stage('Test') {
            steps {
                dir(APP_PATH) {
                    sh """
                    docker run test pytest
                    """
                }
            }
        }

        stage('Kubectl check') {
            steps {
                dir(APP_PATH) {
                    sh """
                    export KUBECONFIG=${KUBECONFIG}
                    kubectl get all
                    """
                }
            }
        }
    }
}
